services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
  db:
    build:
      context: ./db
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
volumes:
  db-volume:
